### ISSUE TITLE
`java.util.NoSuchElementException: List is empty.` on an epsilon reduction

### ISSUE THREAD

**Issue by j-jzk** [j-jzk/klang#43]
```
Exception in thread "main" java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
        at cz.j_jzk.klang.parse.api.ParserBuilder$wrapReduction$1.invoke(ParserBuilder.kt:106)
        at cz.j_jzk.klang.parse.api.ParserBuilder$wrapReduction$1.invoke(ParserBuilder.kt:95)
        at cz.j_jzk.klang.parse.algo.DFAParser.reduce(DFAParser.kt:52)
        at cz.j_jzk.klang.parse.algo.DFAParser.parse(DFAParser.kt:38)
        at cz.j_jzk.klang.parse.algo.DFA.parse(DFAParser.kt:20)
        at cz.j_jzk.klang.parse.ParserWrapper.parse(ParserWrapper.kt:14)
```

**Comment by j-jzk** [comment]
This is because we want to extract the PositionInfo from the first node of the definition.

A temporary solution would be to return a dummy PositionInfo, but that would break sometimes:
```
LIST -> LIST element
LIST -> epsilon
```
In the above grammar, each LIST would have an undefined position.
